[GCC 10] do not test SIMD with wide character types
GCC 10's libstdc++ deleted some `operator<<` overloads to write wide
characters to non-wide streams as these would be treated as integers
instead of characters. One could use wide variants `wstringstream`,
`wstring` instead of the usual `stringstream`, `string`, but at some
places would have to convert between different character
representations.

As wide characters really should only be used for text, DUNE doesn't
really need to support them as numerical types here. So we just drop
the tests using wide character types.

This addresses compiler errors like
```
../dune/common/simd/test.hh:1732:20: error: use of deleted function ‘std::basic_ostream<char, _Traits>& std::operator<<(std::basic_ostream<char, _Traits>&, wchar_t) [with _Traits = std::char_traits<char>]’
In file included from /usr/include/c++/10/iostream:39,
                 from ../dune/common/simd/test.hh:12,
                 from dune/common/simd/test/standardtest_vector_wchar_t.cc:5:
/usr/include/c++/10/ostream:538:5: note: declared here
  538 |     operator<<(basic_ostream<char, _Traits>&, wchar_t) = delete;
```