Revert patch 6394, since it affected dunecontrol.
The dunecontrol output for building dune-common was as follows:
.--- going to build dune-common  ---
.--- calling all for dune-common ---
.--- calling autogen for dune-common ---
.--> dunedoxynize...
Generating doc/doxygen/Doxyfile.in from 
    global style
    and dune-common config
    ... done
.--> libtoolize...
libtoolize: putting auxiliary files in `.'.
libtoolize: linking file `./ltmain.sh'
libtoolize: Remember to add `LT_INIT' to configure.ac.
libtoolize: Consider adding `AC_CONFIG_MACRO_DIR([m4])' to configure.ac and
libtoolize: rerunning libtoolize, to keep the correct libtool macros in-tree.
libtoolize: Consider adding `-I m4' to ACLOCAL_AMFLAGS in Makefile.am.
.--> ERROR: multiple definition of module dune-common
previous defined in:
  /usr/people/nolte/numerics/release-2.1.0/dune-common/dune.module
redefined in:
  /usr/people/nolte/numerics/release-2.1.0/dune-common/dune.module
Execution of dunecontrol terminated due to errors!
.--- Failed to build dune-common ---
Terminating dunecontrol due to previous errors!

[[Imported from SVN: r6395]]