[typetraits.hh] Fix "multiple definitions of isTupleOrDerived".
Error message (line numbers may be off due to additional patches on top of
master in my topic branch):

/home/joe/Projekte/EXA-DUNE/patches/build_paranoia_gcc_4.9_debug/dune-geometry/lib/libdunegeometry.a(referencedomain.cc.o): In function `Dune::Imp::isTupleOrDerived(void const*)':
/home/joe/Projekte/EXA-DUNE/patches/dune-common/dune/common/typetraits.hh:485: multiple definition of `Dune::Imp::isTupleOrDerived(void const*)'
CMakeFiles/finiteelements-connected.dir/finiteelements-connected.cc.o:/home/joe/Projekte/EXA-DUNE/patches/dune-common/dune/common/typetraits.hh:485: first defined here